/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

import Business.Business;

import javax.swing.JPanel;
import Business.Profiles.Profile;
import Business.Profiles.StudentProfile;
import Business.Profiles.EmployeeProfile;

/**
 *
 * @author kal bugrara
 */
public class AdministerPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;

    Business business;

    public AdministerPersonJPanel(Business bz, JPanel jp) {

        CardSequencePanel = jp;
        this.business = bz;
        initComponents();


    }

    public void refreshTable() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPersonId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnCreateAccount = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(30, 290, 80, 23);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage Person Profile");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        jLabel1.setText("Username:");
        add(jLabel1);
        jLabel1.setBounds(60, 170, 70, 17);
        add(txtUsername);
        txtUsername.setBounds(190, 170, 250, 23);

        jLabel3.setText("Person ID:");
        add(jLabel3);
        jLabel3.setBounds(70, 130, 70, 17);
        add(txtPersonId);
        txtPersonId.setBounds(190, 130, 250, 23);

        jLabel4.setText("Password:");
        add(jLabel4);
        jLabel4.setBounds(70, 220, 70, 17);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword);
        txtPassword.setBounds(190, 220, 250, 23);

        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        add(btnCreateAccount);
        btnCreateAccount.setBounds(240, 290, 200, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_BackActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        // TODO add your handling code here:
        
        String personId = txtPersonId.getText().trim();
    String username = txtUsername.getText().trim();
    String password = txtPassword.getText().trim();
    
    if (personId.isEmpty() || username.isEmpty() || password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields!");
        return;
    }
    
    Profile profile = null;
    StudentProfile sp = business.getStudentDirectory().findStudent(personId);
    if (sp != null) {
        profile = sp;
    } else {
        EmployeeProfile ep = business.getEmployeeDirectory().findEmployee(personId);
        if (ep != null) profile = ep;
    }
    
    if (profile == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Person not found!");
        return;
    }
    
    business.getUserAccountDirectory().newUserAccount(profile, username, password);
    javax.swing.JOptionPane.showMessageDialog(this, "User account created successfully!");
    
    txtPersonId.setText("");
    txtUsername.setText("");
    txtPassword.setText("");
    }//GEN-LAST:event_btnCreateAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPersonId;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
