/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Profiles.Profile;


import javax.swing.JPanel;

/**
 *
 * @author kal bugrara
 */
public class ManagePersonsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;


    public ManagePersonsJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        txtPersonId.setEditable(false);
        txtPersonId.setText(generatePersonId());

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPersonID = new javax.swing.JLabel();
        txtPersonId = new javax.swing.JTextField();
        lblRole = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        btnRegisterPerson = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(30, 340, 80, 23);

        Next.setText("Next >>");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        add(Next);
        Next.setBounds(500, 340, 80, 23);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage Personnel (HR)");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        lblName.setText("Name:");
        add(lblName);
        lblName.setBounds(40, 90, 38, 17);
        add(txtName);
        txtName.setBounds(90, 90, 260, 23);

        lblEmail.setText("Email:");
        add(lblEmail);
        lblEmail.setBounds(40, 140, 36, 17);
        add(txtEmail);
        txtEmail.setBounds(90, 140, 260, 23);

        lblPersonID.setText("Person ID:");
        add(lblPersonID);
        lblPersonID.setBounds(20, 190, 70, 17);
        add(txtPersonId);
        txtPersonId.setBounds(90, 190, 260, 23);

        lblRole.setText("Role:");
        add(lblRole);
        lblRole.setBounds(30, 240, 30, 17);

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Faculty", " ", " " }));
        add(cmbRole);
        cmbRole.setBounds(90, 240, 260, 23);

        btnRegisterPerson.setText("Register Person");
        btnRegisterPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterPersonActionPerformed(evt);
            }
        });
        add(btnRegisterPerson);
        btnRegisterPerson.setBounds(250, 340, 130, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
 //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");

    }//GEN-LAST:event_BackActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        
        AdministerPersonJPanel mppd = new AdministerPersonJPanel(business, CardSequencePanel);
        CardSequencePanel.add(mppd);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_NextActionPerformed

    private void btnRegisterPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterPersonActionPerformed
        // TODO add your handling code here:
        
        validateAndRegister();
    }//GEN-LAST:event_btnRegisterPersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Next;
    private javax.swing.JButton btnRegisterPerson;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPersonID;
    private javax.swing.JLabel lblRole;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPersonId;
    // End of variables declaration//GEN-END:variables
private String generatePersonId() {
    return "P" + System.currentTimeMillis();
}

private void validateAndRegister() {
    String name = txtName.getText().trim();
    String email = txtEmail.getText().trim();
    String personId = txtPersonId.getText();
    String role = (String) cmbRole.getSelectedItem();
    
    if (name.isEmpty() || email.isEmpty() || role == null || role.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Please fill in all fields!",
            "Validation Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    if (!email.contains("@")) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Please enter a valid email address!",
            "Validation Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Check for duplicate email
    for (Person p : business.getPersonDirectory().getPersonList()) {
        if (p.getEmail().equalsIgnoreCase(email)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "A person with this email already exists!",
                "Duplicate Email",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
    }
    
    // Check for duplicate ID 
    Person existingPerson = business.getPersonDirectory().findPerson(personId);
    if (existingPerson != null) {
        txtPersonId.setText(generatePersonId());
        javax.swing.JOptionPane.showMessageDialog(this,
            "ID conflict detected. Generated new ID: " + txtPersonId.getText(),
            "Warning",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Create person with name and email
    Person person = business.getPersonDirectory().newPerson(personId, name, email);

    Profile profile = null;

    if (role.equals("Student")) {
        profile = business.getStudentDirectory().newStudentProfile(person);
    } else if (role.equals("Faculty")) {
        profile = business.getEmployeeDirectory().newEmployeeProfile(person);
    }
    
    // Create User Account
    String username = name.toLowerCase().replace(" ", "");
    String defaultPassword = "pass123";
    business.getUserAccountDirectory().newUserAccount(profile, username, defaultPassword);
    
    javax.swing.JOptionPane.showMessageDialog(this,
        "Person registered successfully!\n" +
        "Name: " + name + "\n" +
        "Email: " + email + "\n" +
        "ID: " + personId + "\n" + 
        "Username: " + username + "\n" +
        "Password: " + defaultPassword,
        "Success",
        javax.swing.JOptionPane.INFORMATION_MESSAGE);
    
    clearForm();
}

private void clearForm() {
    txtName.setText("");
    txtEmail.setText("");
    txtPersonId.setText(generatePersonId());
    cmbRole.setSelectedIndex(0);
}
}
