/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole;
import Business.Business;
import javax.swing.JPanel;

/**
 *
 * @author aasikaleem
 */
public class AnalyticsDashboardJPanel extends javax.swing.JPanel {
    Business business;
    JPanel CardSequencePanel;

    /**
     * Creates new form AnalyticsDashboardJPanel
     */
    public AnalyticsDashboardJPanel(Business bz, JPanel jp) {
    CardSequencePanel = jp;
    this.business = bz;
    initComponents();
    populateAnalytics();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnalyticsDashboard = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnalytics = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 204));

        lblAnalyticsDashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblAnalyticsDashboard.setText("Analytics Dashboard");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblAnalytics.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Metric", "vlaue"
            }
        ));
        jScrollPane1.setViewportView(tblAnalytics);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lblAnalyticsDashboard))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblAnalyticsDashboard)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
         CardSequencePanel.remove(this);
         ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnalyticsDashboard;
    private javax.swing.JTable tblAnalytics;
    // End of variables declaration//GEN-END:variables
private void populateAnalytics() {
    javax.swing.table.DefaultTableModel model = 
        (javax.swing.table.DefaultTableModel) tblAnalytics.getModel();
    model.setRowCount(0);
    
    int totalUsers = business.getUserAccountDirectory().getUserAccountList().size();
    int totalStudents = business.getStudentDirectory().getStudentList().size();
    int totalFaculty = business.getEmployeeDirectory().getEmployeeList().size();
    
    model.addRow(new Object[]{"Total Users", totalUsers});
    model.addRow(new Object[]{"Total Students", totalStudents});
    model.addRow(new Object[]{"Total Faculty", totalFaculty});
    model.addRow(new Object[]{"Total Persons", business.getPersonDirectory().getPersonList().size()});
}
}
