/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.UserAccounts.UserAccount;
import javax.swing.JPanel;

/**
 *h
 * @author kal bugrara
 */

public class AdminUserAccount extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;

    UserAccount selecteduseraccount;

    ManageUserAccountsJPanel parentPanel;
    
  public AdminUserAccount(UserAccount sua, JPanel jp, ManageUserAccountsJPanel parent) {
    CardSequencePanel = jp;
    selecteduseraccount= sua;
    parentPanel = parent;
    initComponents();
    populateUserAccountData();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        lblAdminUserAccount = new javax.swing.JLabel();
        Back1 = new javax.swing.JButton();
        lblUnserName = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        lblRole = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        lblLastActivity = new javax.swing.JLabel();
        txtLastActivity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLastUpdated = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        Back.setText("Update>>");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(480, 290, 100, 23);

        lblAdminUserAccount.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblAdminUserAccount.setText("Administer User Account");
        add(lblAdminUserAccount);
        lblAdminUserAccount.setBounds(21, 20, 550, 28);

        Back1.setText("<< Back");
        Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back1ActionPerformed(evt);
            }
        });
        add(Back1);
        Back1.setBounds(40, 290, 100, 23);

        lblUnserName.setText("Username:");
        add(lblUnserName);
        lblUnserName.setBounds(60, 80, 70, 17);
        add(txtUsername);
        txtUsername.setBounds(140, 80, 240, 23);

        lblStatus.setText("Status:");
        add(lblStatus);
        lblStatus.setBounds(70, 130, 41, 17);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive", "Suspended", " " }));
        add(cmbStatus);
        cmbStatus.setBounds(140, 130, 240, 23);

        lblRole.setText("Role:");
        add(lblRole);
        lblRole.setBounds(70, 180, 30, 17);
        add(txtRole);
        txtRole.setBounds(130, 180, 260, 23);

        lblLastActivity.setText("Last Activity:");
        add(lblLastActivity);
        lblLastActivity.setBounds(40, 220, 80, 17);
        add(txtLastActivity);
        txtLastActivity.setBounds(130, 220, 260, 23);

        jLabel3.setText("Last Update: ");
        add(jLabel3);
        jLabel3.setBounds(40, 250, 80, 17);
        add(txtLastUpdated);
        txtLastUpdated.setBounds(130, 250, 260, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:

      String newStatus = (String) cmbStatus.getSelectedItem();
    selecteduseraccount.setStatus(newStatus);
    
    javax.swing.JOptionPane.showMessageDialog(this, 
        "User account updated successfully!", 
        "Success", 
        javax.swing.JOptionPane.INFORMATION_MESSAGE);
    
    CardSequencePanel.remove(this);
    parentPanel.refreshTable();
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);

    }//GEN-LAST:event_BackActionPerformed

    private void Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back1ActionPerformed
        // TODO add your handling code here:
          CardSequencePanel.remove(this);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);

    
    }//GEN-LAST:event_Back1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Back1;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAdminUserAccount;
    private javax.swing.JLabel lblLastActivity;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUnserName;
    private javax.swing.JTextField txtLastActivity;
    private javax.swing.JTextField txtLastUpdated;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
private void populateUserAccountData() {
    if (selecteduseraccount != null) {
        txtUsername.setText(selecteduseraccount.getUserLoginName());
        cmbStatus.setSelectedItem(selecteduseraccount.getStatus());
        txtRole.setText(selecteduseraccount.getRole());
        txtLastActivity.setText(selecteduseraccount.getLastActivity());
        txtLastUpdated.setText(selecteduseraccount.getLastUpdated());
        
        txtUsername.setEditable(false);
        txtRole.setEditable(false);
        txtLastActivity.setEditable(false);
        txtLastUpdated.setEditable(false);
    }
}
}
