/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

/**
 *
 * @author User
 */
import Business.Business;
import Business.Profiles.StudentProfile;


import info5100.university.example.CourseSchedule.CourseLoad;
import info5100.university.example.CourseSchedule.SeatAssignment;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import info5100.university.example.CourseCatalog.Course;


public class StudentCourseWorkJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentCourseWorkJPanel
     */
   private Business business;
    private StudentProfile studentProfile;
    private info5100.university.example.Persona.StudentProfile universityStudent; // academic
    private HashMap<String, Boolean> assignmentSubmitted = new HashMap<>();

    public StudentCourseWorkJPanel(Business business,
                               StudentProfile studentProfile,
                               info5100.university.example.Persona.StudentProfile universityStudent) {
    initComponents();
    this.business = business;
    this.studentProfile = studentProfile;
    this.universityStudent = universityStudent;
    populateTable();    
    updateGPA();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCoursework = new javax.swing.JTable();
        btnSubmitAssignment = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        lblGPA = new javax.swing.JLabel();

        jLabel1.setText("Coursework and progress");

        tblCoursework.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCoursework);

        btnSubmitAssignment.setText("Submit Assignment");
        btnSubmitAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitAssignmentActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        lblGPA.setText("Currfent GPA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRefresh)
                            .addComponent(btnSubmitAssignment))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblGPA)
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnSubmitAssignment)
                .addGap(19, 19, 19)
                .addComponent(lblGPA)
                .addGap(4, 4, 4)
                .addComponent(btnRefresh)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
        updateGPA();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSubmitAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitAssignmentActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblCoursework.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a course to submit assignment.");
        return;
    }
    String courseId = (String) tblCoursework.getValueAt(selectedRow, 0);
    assignmentSubmitted.put(courseId, true);
    JOptionPane.showMessageDialog(this, "Assignment submitted for " + courseId + "!");
    populateTable();
    updateGPA();
    }//GEN-LAST:event_btnSubmitAssignmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSubmitAssignment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JTable tblCoursework;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
          javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblCoursework.getModel();
    model.setRowCount(0);

    info5100.university.example.CourseSchedule.CourseLoad courseLoad = universityStudent.getCurrentCourseLoad();
    if (courseLoad == null) return;

    for (info5100.university.example.CourseSchedule.SeatAssignment seat : courseLoad.getSeatAssignments()) {
       info5100.university.example.CourseCatalog.Course course = seat.getCourseOffer().getSubjectCourse();

        String courseId = course.getCOurseNumber();  
        String courseName = "Course " + course.getCOurseNumber();

        String status = assignmentSubmitted.getOrDefault(courseId, false) ? "Submitted" : "Pending";
        String grade = seat.GetCourseStudentScore() == 0 ? "Not Graded" :
                       String.valueOf(seat.GetCourseStudentScore());
        model.addRow(new Object[]{courseId, courseName, status, grade});
    }
}
    private void updateGPA() {
    info5100.university.example.CourseSchedule.CourseLoad courseLoad = universityStudent.getCurrentCourseLoad();
    if (courseLoad == null) {
        lblGPA.setText("Current GPA: N/A");
        return;
    }

    float totalScore = courseLoad.getSemesterScore();
    float totalCourses = courseLoad.getSeatAssignments().size();
    float gpa = totalCourses > 0 ? totalScore / totalCourses : 0;

    lblGPA.setText("Current GPA: " + String.format("%.2f", gpa));
}
}