/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

/**
 *
 * @author User
 */

import info5100.university.example.CourseSchedule.CourseLoad;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.CourseSchedule.SeatAssignment;
import info5100.university.example.CourseSchedule.Seat;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.CourseCatalog.Course;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class StudentCourseRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentCourseRegistrationJPanel
     */
    private Department department;
    private StudentProfile studentProfile;
    public StudentCourseRegistrationJPanel(Department department, StudentProfile studentProfile) {
        initComponents();
        this.department = department;
        this.studentProfile = studentProfile;
        populateCourseTable(department.getCourseSchedule("Fall2025"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbSearchType = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        btnEnroll = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();
        lblCredits = new javax.swing.JLabel();

        jLabel1.setText("Course Registration");

        jLabel2.setText("Term");

        jLabel3.setText("Criteria");

        cmbSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course ID", "Teacher", "Semester" }));
        cmbSearchType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSearchTypeActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCourses);

        btnEnroll.setText("Enroll");

        btnDrop.setText("Drop Course");

        lblCredits.setText("Total enrolled credits");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnSearch)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDrop)
                    .addComponent(btnEnroll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(lblCredits)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnroll)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCredits)
                        .addGap(3, 3, 3)))
                .addComponent(btnDrop)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSearchTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSearchTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSearchTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbSearchType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JTable tblCourses;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

   private void populateCourseTable(CourseSchedule courseSchedule) {
    DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
    model.setRowCount(0);

    if (courseSchedule == null) {
        JOptionPane.showMessageDialog(this, "No course schedule available for this term.");
        return;
    }

    model.setColumnIdentifiers(new String[]{
        "Course ID", "Course Name", "Instructor", "Credits", "Available Seats"
    });

    try {
        // Access private schedule list in CourseSchedule
        java.lang.reflect.Field scheduleField = CourseSchedule.class.getDeclaredField("schedule");
        scheduleField.setAccessible(true);
        @SuppressWarnings("unchecked")
        ArrayList<CourseOffer> offers = (ArrayList<CourseOffer>) scheduleField.get(courseSchedule);

        for (CourseOffer offer : offers) {
            if (offer == null || offer.getSubjectCourse() == null) continue;

            String courseId = offer.getCourseNumber();

            // ✅ Fix 1: Course name getter
            // (Your Course.java likely has getCourseName() or getCOurseName())
            String courseName;
            try {
                courseName = offer.getSubjectCourse().getCourseName();
            } catch (Exception e) {
                // fallback if method name is different
                courseName = offer.getSubjectCourse().getCOurseNumber();
            }

            int credits = offer.getCreditHours();

            // ✅ Fix 2: Faculty name getter
            String instructor = "Unassigned";
            FacultyProfile facultyProfile = offer.getFacultyProfile();
            if (facultyProfile != null) {
                try {
                    // if Person class has getName()
                    instructor = facultyProfile.getPerson().getName();
                } catch (Exception e) {
                    // fallback in case method name differs
                    instructor = "Unknown";
                }
            }

            // ✅ Seat availability
            java.lang.reflect.Field seatField = CourseOffer.class.getDeclaredField("seatlist");
            seatField.setAccessible(true);
            @SuppressWarnings("unchecked")
            ArrayList<Seat> seats = (ArrayList<Seat>) seatField.get(offer);

            int totalSeats = seats.size();
            int occupiedSeats = 0;
            for (Seat s : seats) {
                if (s.isOccupied()) occupiedSeats++;
            }
            int availableSeats = totalSeats - occupiedSeats;

            model.addRow(new Object[]{courseId, courseName, instructor, credits, availableSeats});
        }

        updateEnrolledCredits();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error populating course table: " + e.getMessage());
    }
    
}
   private void updateEnrolledCredits() {
    int totalCredits = 0;
    CourseLoad currentLoad = studentProfile.getCurrentCourseLoad();

    if (currentLoad != null) {
        for (SeatAssignment sa : currentLoad.getSeatAssignments()) {
            if (sa != null) {
                totalCredits += sa.getCreditHours();
            }
        }
    }

    lblCredits.setText("Total enrolled credits: " + totalCredits);
}
}

