/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole;

import Business.Business;
import Business.Profiles.EmployeeProfile;
import Business.Profiles.StudentProfile;
import javax.swing.JPanel;

/**
 *
 * @author aasikaleem
 */
public class ManageFacultyJPanel extends javax.swing.JPanel {
    
    Business business;
    JPanel CardSequencePanel;

    /**
     * Creates new form ManageFacultyJPanel
     */
   public ManageFacultyJPanel(Business bz, JPanel jp) {
    CardSequencePanel = jp;
    this.business = bz;
    initComponents();
    populateTable();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFaculty = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        lblManageFaculty = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        lblSearchby = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        cmbSearchType = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblFaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                " Faculty ID", "Name", "Department", "Email"
            }
        ));
        jScrollPane1.setViewportView(tblFaculty);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        lblManageFaculty.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblManageFaculty.setText("Manage Faculty");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lblSearchby.setText("Search By:");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        cmbSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Faculty ID", "Name", "Department", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSearchby)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblManageFaculty)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(95, 95, 95)
                        .addComponent(btnViewDetails)
                        .addGap(65, 65, 65)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManageFaculty)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchby)
                    .addComponent(cmbSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDetails)
                    .addComponent(btnBack)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:

      String searchType = (String) cmbSearchType.getSelectedItem();
    String searchText = txtSearch.getText().trim();

    if (searchText.isEmpty()) {
        populateTable();
        return;
    }

    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) tblFaculty.getModel();
    model.setRowCount(0);

    for (EmployeeProfile faculty : business.getEmployeeDirectory().getEmployeeList()) {
        boolean match = false;
        String personId = faculty.getPerson().getPersonId();

        if (searchType.equals("Faculty ID") && personId.toLowerCase().contains(searchText.toLowerCase())) {
            match = true;
        } else if (searchType.equals("Name") && personId.toLowerCase().contains(searchText.toLowerCase())) {
            match = true;
        } else if (searchType.equals("Department")) {
            match = true;
        }

      if (match) {
    Object[] row = new Object[4];
    row[0] = faculty.getPerson().getPersonId();
    row[1] = faculty.getPerson().getName();
    row[2] = "Information Systems";
    row[3] = faculty.getPerson().getEmail();
    model.addRow(row);
      }
    }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        

        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
       javax.swing.JOptionPane.showMessageDialog(this,
        "View Details functionality coming soon!",
        "Info",
        javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblFaculty.getSelectedRow();
    
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Please select a faculty member to edit!",
            "No Selection",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    javax.swing.JOptionPane.showMessageDialog(this,
        "Edit functionality coming soon!",
        "Info",
        javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

       int selectedRow = tblFaculty.getSelectedRow();
    
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Please select a faculty member to delete!",
            "No Selection",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String facultyId = tblFaculty.getValueAt(selectedRow, 0).toString();
    
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
        "Are you sure you want to delete faculty " + facultyId + "?",
        "Confirm Delete",
        javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        boolean deleted = business.getEmployeeDirectory().deleteEmployee(facultyId);
        if (deleted) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Faculty deleted successfully!",
                "Success",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            populateTable();
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JComboBox<String> cmbSearchType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManageFaculty;
    private javax.swing.JLabel lblSearchby;
    private javax.swing.JTable tblFaculty;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
private void populateTable() {
    javax.swing.table.DefaultTableModel model = 
        (javax.swing.table.DefaultTableModel) tblFaculty.getModel();
    model.setRowCount(0);
    
    for (EmployeeProfile faculty : business.getEmployeeDirectory().getEmployeeList()) {
        Object[] row = new Object[4];
        row[0] = faculty.getPerson().getPersonId();
        row[1] = faculty.getPerson().getName();
        row[2] = "Information Systems";
        row[3] = faculty.getPerson().getEmail();
        model.addRow(row);
    }
}

}
